name: HellEssentials
version: 1.0
description: An essential plugin
author: Kinderix
main: me.kinderix.HellEssentials.HellMain
api-version: 1.17
load: STARTUP
softdepend:
  - LuckPerms
commands:
  feed:
    description: Feed yourself!
    permission: hellessentials.feed
    usage: Syntax error! Simply type /feed to feed yourself.
  heal:
    description: Heal yourself!
    permission: hellessentials.heal
    usage: Syntax error! Simply type /heal to heal yourself.
  clear:
    description: Clear your inventory!
    permission: hellessentials.clear
    usage: Syntax error! Simply type /clear to clear your inventory.
  gmc:
    description: Changes gamemode to creative!
    permission: hellessentials.gamemode.creative
    usage: Syntax error! Simply type /gmc to change to gamemode creative.
  gms:
    description: Changes gamemode to survival!
    permission: hellessentials.gamemode.survival
    usage: Syntax error! Simply type /gms to change gamemode to survival.
  gmsp:
    description: Changes gamemode to spectator!
    permission: hellessentials.gamemode.spectator
    usage: Syntax error! Simply type /gmsp to change gamemode to spectator.
  gma:
    description: Changes gamemode to adventure!
    permission: hellessentials.gamemode.adventure
    usage: Syntax error! Simply type /gma to change gamemode to adventure.
  tp:
    description: Teleport to a player
    permission: hellessentials.tp
    usage: Syntax error! Simply type /tp to teleport.
  kick:
    description: Kicks a player
    permission: hellessentials.kick
    usage: Syntax error! Simply type /kick to kick a player.
  mutechat:
    description: Mutes the chat
    permission: hellessentials.mutechat.use
  permissions:
    hellessentials.*:
      description: Gives access to all HellEssentials commands
      children:
        hellessentials.feed: true
        hellessentials.heal: true
        hellessentials.clear: true
        hellessentials.gamemode.*: true
        hellessentials.tp: true
        hellessentials.kick: true
        hellessentials.mutechat.use: true
        hellessentials.mutechat.bypass: true
    hellessentials.gamemode.*:
      description: Gives access to all gamemodes
      children:
        hellessentials.gamemode.creative: true
        hellessentials.gamemode.survival: true
        hellessentials.gamemode.spectator: true
        hellessentials.gamemode.adventure: true
    hellessentials.feed:
      description: Allows you to feed yourself
      default: true
    hellessentials.heal:
      description: Allows you to heal yourself
      default: false
    hellessentials.clear:
      descriptiron: Allows to clear your or someone's inventory
      default: false
    hellessentials.gamemode.creative:
      description: Allow you to change gamemode to creative
      default: false
    hellessentials.gamemode.survival:
      description: Allow you to change gamemode to survival
      default: false
    hellessentials.gamemode.spectator:
      description: Allow you to change gamemode to spectator
      default: false
    hellessentials.gamemode.adventure:
      description: Allow you to change gamemode to adventure
      default: false
    hellessentials.tp:
      description: Allow you to teleport to a player
      default: false
    hellessentials.kick:
      description: Allow you to kick a player
      default: false
    hellessentials.mutechat.use:
      description: Allow you to mute the chat
      default: false
    hellessentials.mutechat.bypass:
      description: Allow you to bypass mutechat
      default: false